name: CI

on:
  pull_request:
  push:
    branches: [ master ]

env:
  VCPKG_GIT_COMMIT: '7d34ab302a0d26fcbf2fead87e969691cf2bb12c'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v1
        with:
          lfs: 'true'
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_GIT_COMMIT }}
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'default'
          buildPreset: 'debug'

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v1
        with:
          lfs: 'true'
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_GIT_COMMIT }}
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'default'
          buildPreset: 'debug'

  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v1
        with:
          lfs: 'true'
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_GIT_COMMIT }}
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'default'
          buildPreset: 'debug'
